# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]
prepend_keymap = [
  { on = [ "c", "a" ], run = "plugin ouch --args=zip", desc = "Compress with ouch"},
  { on = [ "c", "m" ], run = "plugin chmod", desc = "Chmod on selected files"},
  { on = [ "l" ], run = "plugin --sync smart-enter", desc = "Enter the child directory, or open the file" },
  { on = [ "M" ], run = "plugin --sync max-preview", desc = "Maximize or restore preview"}
]

[input]
prepend_keymap = [
  { on = [ "<Esc>" ], run = "close", desc = "Cancel input" },
]
