[manager]
ratio          = [ 1, 3, 4 ]
sort_sensitive = false
sort_dir_first = true
show_hidden    = true
show_symlink   = true

[preview]
max_width     = 1200
max_height    = 1800
image_filter  = "triangle"
image_quality = 80

[plugin]
prepend_previewers = [
  { mime = "text/csv", exec = "miller" },
  { name = "*.md", exec = "glow" },
]
